# Generated by Django 3.2.7 on 2021-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0002_auto_20210917_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=150)),
                ('image', models.ImageField(default='pix.jpg', upload_to='products')),
            ],
        ),
    ]
