# Generated by Django 3.2.7 on 2021-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0003_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slide',
        ),
    ]
