# Generated by Django 3.2.7 on 2021-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0005_shopcart_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='min',
            field=models.IntegerField(default=1),
        ),
    ]
